Repository sassoftware/vscode-sas-extension, pull requests merged in 2023-09, with the labels that each got.

#473 feat: provide an easy way for users to specify the ods style of the results and automatically use a style that reasonably matches the vs code theme by default
  CHANGELOG.md
  client/src/commands/run.ts
  client/src/components/notebook/Controller.ts
  client/src/components/utils.ts
  package.json
  package.nls.de.json
  package.nls.json
  package.nls.zh-cn.json
Labels: feature request, testing-complete

#496 feat: change output html option to more logical/consistent ID and re-order options
  client/src/commands/run.ts
  client/src/components/utils.ts
  package.json
  package.nls.de.json
  package.nls.json
  package.nls.zh-cn.json
Labels: verification-needed

#451 feat: refined indentation parsed programmatically
  language-configuration.json
  package.json
  server/src/sas/CodeZoneManager.ts
  server/src/sas/FormatOnTypeProvider.ts
  server/src/sas/LanguageServiceProvider.ts
  server/src/server.ts
Labels: testing-complete

#487 fix: correctly re-open files for content rename
  client/src/components/ContentNavigator/ContentDataProvider.ts
  client/src/components/ContentNavigator/index.ts
Labels: testing-complete

#509 fix: call routine autocomplete
  server/src/sas/CodeZoneManager.ts
Labels: testing-complete

#508 fix: add proper content-type for rename (#507)
  client/src/components/ContentNavigator/ContentModel.ts
Labels: testing-complete

#505 fix: do not rename when cancel input (#504)
  client/src/components/ContentNavigator/index.ts
Labels: testing-complete

#444 feat: run SAS code via vscode tasks
  client/src/commands/run.ts
  client/src/components/Helper/SasCodeHelper.ts
  client/src/components/Helper/SettingHelper.ts
  client/src/components/LogChannel.ts
  client/src/components/notebook/Controller.ts
  client/src/components/tasks/SasTaskProvider.ts
  client/src/components/tasks/SasTasks.ts
  client/src/components/utils.ts
  client/src/node/extension.ts
  connect-and-run.md
  l10n/bundle.l10n.zh-cn.json
  package.json
Labels: testing-complete

#512 fix: update high contrast data viewer theming
  client/src/webview/DataViewer.css
  client/src/webview/DataViewer.tsx
Labels: testing-complete

#524 Assign _SASPROGRAMFILE macro-variable to full path and filename of submitted SAS program (Local SAS 9.4)
  client/src/commands/run.ts
  client/src/components/Helper/SasCodeHelper.ts
  client/test/components/Helper/SasCodeHelper.test.ts
Labels: testing-complete

#513 feat: option to control the default placement of Result panel
  client/src/commands/run.ts
  client/src/components/Helper/SettingHelper.ts
  client/src/components/ResultPanel.ts
  client/src/components/tasks/SasTasks.ts
  package.json
  package.nls.json
Labels: testing-complete

#534 fix: rename folder failed (#533)
  client/src/components/ContentNavigator/ContentModel.ts
Labels: testing-complete

#538 fix: associate sas-notebook with sasnb only
  client/src/components/ContentNavigator/convert.ts
  client/src/components/ContentNavigator/index.ts
  client/src/components/ContentNavigator/utils.ts
  client/test/components/ContentNavigator/convert.test.ts
  package.json
Labels: testing-complete
